/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Prevent App Nap
 #	author : miyako
 #	2018/11/19
 #
 # --------------------------------------------------------------------------------*/

#include <mutex>

// --- Prevent App Nap


void OnCloseProcess(PA_PluginParameters params);
void OnStartup();
void OnExit();

void BEGIN_IMPORTANT_ACTIVITY(PA_PluginParameters params);
void END_IMPORTANT_ACTIVITY(PA_PluginParameters params);
